# Build customization
git:
  short_hash: true
builds:
  - env:
    - CGO_ENABLED=0
  - main: ./
    binary: KuronanDash
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
# Archive customization
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    amd64: x86_64
    windows: Windows
    darwin: macOS
    linux: Linux
  files:
    - LICENSE
    - README.md
