builds:
  - main: ./
    binary: KuronanDash
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

archives:
  - format: zip
    replacements:
      amd64: 64-bit
      386: 32-bit
      windows: Windows
      darwin: macOS
      linux: Linux
    files:
      - LICENSE
      - README.md
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256
