language: go

os:
  - linux
  - osx

go:
  - 1.13.x

addons:
  apt:
    packages:
      - libgl1-mesa-dev 
      - xorg-dev
      - libasound2-dev

before_install:
  - go get -v golang.org/x/lint/golint
  - export DISPLAY=:99.0

services:
  - xvfb

jobs:
  include:
    - stage: lint and test
      name: check by golint
      script: golint ./...
      if: os = linux
    - name: check by go vet
      script: go vet ./...
      if: os = linux
    - name: test
      script: go test -v -cover ./...
      if: os = linux
    - stage: build
      name: build darwin on osx
      script: CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 go build -o kuronan-dash_macOS_amd64
      if: os = osx
    - name: build windows on linux 
      script: CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build -o kuronan-dash_windows_amd64.exe
      if: os = linux
    - name: build linux on linux
      script: CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o kuronan-dash_linux_amd64
      if: os = linux
