language: go
sudo: true
go:
  - tip
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libgl1-mesa-dev xorg-dev libasound2-dev
  - go get github.com/kardianos/govendor
script:
  - govendor sync
after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
