language: go
sudo: true
go:
  - "1.13"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libgl1-mesa-dev xorg-dev libasound2-dev
script:
  - go vet ./...
after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
