language: go
sudo: true
go:
  - tip
before_install:
  - sudo apt install libgl1-mesa-dev xorg-dev
  - go get github.com/kardianos/govendor
  - go get github.com/mattn/goveralls
script:
  - govendor sync
  - $HOME/gopath/bin/goveralls -service=travis-ci
after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
